### PR TITLE
Making changes to the socioeconomics pages.

### PR DESCRIPTION
**Pull request by simaob**
[PIVOTAL](https://www.pivotaltracker.com/story/show/164210158)

I have only just started adding the Sex_ratio_child to the list of available indicators, but it turns out that we don't have national data for this indicator. Javi, I've assigned it to you and would ask you to have a look as you have dealt with a similar situation for the Energy section of the country context, right?

Though I'd probably suggest prioritising the Indonesia update with the merging of the side by side charts ahead of this one.

### CODE REVIEW

**Comment by weberjavi** [comment]
Taking care of that one ☝️

**Comment by weberjavi** [comment]
@simaob take a look at this ☝️ 
Added Child sex ratio and also impossibility to add more than 4 elements to the chart (via legend plus button)

**Comment by weberjavi** [comment]
Addressed also that one
https://basecamp.com/1756858/projects/15229632/todos/379872252

**Comment by simaob** [comment]
Thanks, Javi! Looks good to me =)

**Pull request merged**
