### PR TITLE
allow multiple sources for socioeconomic indicators

### PR DESCRIPTION
**Pull request by tsubik**
This PR and fixing the data on staging should help with multiple sources for socioeconomic indicators.

image

### CODE REVIEW

**Comment by simaob** [comment]
@tsubik something is amiss, when I run this branch the homepage is broken.

**Comment by tsubik** [comment]
Hmm, let me check.

**Comment by tsubik** [comment]
Maybe you have to reimport data?

**Comment by simaob** [comment]
I did. I get these errors in the console: 

Screenshot 2019-07-05 at 15 58 12

**Pull request merged**
