### PR TITLE
Feature/text management

### PR DESCRIPTION
**Pull request by tsubik**
Bringing text management to India platform. Backend + frontend.

```
bundle exec rake db:migrate
```

image

### CODE REVIEW

**Comment by simaob** [comment]
On the Climate Goals tab when I change the "Overview" Title or Description it doesn't seem to be applied. Wondering if maybe these two are not hooked up on the front?

**Comment by simaob** [comment]
The other ones work! =)

**Comment by tsubik** [comment]
Ohh, yeah that might be a case. Frontend not updated. Let me check.

**Comment by tsubik** [comment]
Ok. Fixed. But I removed the overview description. Description is taken from NDC flagship API. Also, navigation links are not changeable. If they want to change them we can add extra keys.

**Pull request merged**
