### PR TITLE
Feature/remove metric historical emissions

### PR DESCRIPTION
**Pull request by Bluesmile82**
- Removes metric dropdown and code - Only absolute values are shown
- Fixes a problem with the margin in Energy chart - We can only use numbers, no strings

image
image

### CODE REVIEW

**Comment by tsubik** [comment]
Also, there should be a small margin between the chart and the bottom legend.

**Comment by Bluesmile82** [comment]
I've changed some margins and added a missing unit in Historical emissions. After talking with design we can't change the selector width without changing all. What we need to fix is the long texts that are exceeding the width in the selectors. I will do a PR in components for this. Also maybe adding a default margin between chart and legend

**Comment by tsubik** [comment]
Hmm, so we can resize them all a little bit. I wouldn't think that different widths for selectors could be a problem here. We normally expect longer texts for some data.

**Comment by Bluesmile82** [comment]
Yes, there was one exception I think. But they should have a standard width determined by the grid

**Comment by Bluesmile82** [comment]
OK, It seems that the selectors were a bit wider than that 2 grid spaces on the designs. I have changed them and standardise with the rest of the app. Ready again!

image

**Comment by tsubik** [comment]
Looking great :+1:

**Pull request merged**
