### PR TITLE
Feature/climate finance

### PR DESCRIPTION
**Pull request by Bluesmile82**
This PR adds the climate finance section. To get the data from climate-finance you might have to run:
```
bundle exec rake db:migrate
bundle exec rake db:admin_boilerplate:create
bundle exec rake db:import
```
Note:
- The overlapping of the unit and the colors in the tooltip will be fixed after releasing this PR: https://github.com/ClimateWatch-Vizzuality/climate-watch-components/pull/110

image

### CODE REVIEW

**Comment by Bluesmile82** [comment]
image
Ready again!

**Comment by tsubik** [comment]
Oops, conflicts

**Comment by Bluesmile82** [comment]
Conflicts fixed 👍

**Comment by tsubik** [comment]
Great :+1: merging.

**Pull request merged**
